-- Generated by nwg-displays on 2026-09-06 at 08:19:39. Do not edit manually.

hl.monitor({
    output = "eDP-2",
    mode = "2560x1600@120.01",
    position = "0x0",
    scale = 1.5000000000000004,
    vrr = 0
})
